### ISSUE TITLE
Linking time error on MacOS

### ISSUE THREAD

**Issue by iankuan** [oopsmonk/iota_esp32_cashier#1]
Environment
- MacOS Version 10.13.6
- `Gcc -v`
```
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
```

Building message:
```bash
[100%] Generating ld/esp32.project.ld
Traceback (most recent call last):
  File "/Users/yenWu/esp/esp-idf/tools/ldgen/ldgen.py", line 150, in <module>
    main()
  File "/Users/yenWu/esp/esp-idf/tools/ldgen/ldgen.py", line 114, in main
    sdkconfig = SDKConfig(kconfig_file, config_file)
  File "/Users/yenWu/esp/esp-idf/tools/ldgen/sdkconfig.py", line 50, in __init__
    self.config = kconfiglib.Kconfig(kconfig_file)
  File "/Users/yenWu/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 656, in __init__
    self.top_node)  # prev_node
  File "/Users/yenWu/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1587, in _parse_block
    prev_node)
  File "/Users/yenWu/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1636, in _parse_block
    node)         # prev_node
  File "/Users/yenWu/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1614, in _parse_block
    node)             # prev_node
  File "/Users/yenWu/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1583, in _parse_block
    self._enter_file(sourced_file)
  File "/Users/yenWu/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1167, in _enter_file
    .format(self._filename, self._linenr, e.message))
IOError: /Users/yenWu/esp/iota_esp32_cashier/main/Kconfig.projbuild:100: Could not open '../components/ST7735/Kconfig' (ENOENT: No such file or directory). Perhaps the $srctree environment variable (which was unset) is set incorrectly. Note that the current value of $srctree is saved when the Kconfig instance is created (for consistency and to cleanly separate instances). Also note that e.g. $FOO in a 'source' statement does not refer to the environment variable FOO, but rather to the Kconfig Symbol FOO (which would commonly have 'option env="FOO"' in its definition).
make[2]: *** [esp-idf/esp32/ld/esp32.project.ld] Error 1
make[1]: *** [esp-idf/esp32/CMakeFiles/__ldgen_output_esp32.project.ld.dir/all] Error 2
make: *** [all] Error 2
make failed with exit code 2
```

**Comment by iankuan** [comment]
It's built on latest version of `esp-idf`. I should change to tag 3.2.2.
